PUT http://localhost:3001/api/users/5d09e7c6a06debc0a06b598b
Content-Type: application/json

{
    "name":  "Jorma",
    "username": "zzzz",
    "favorites": {
        "events": [
        {
            "id" : "popopop"
            },
        {
             "id":"ioioioioi"}
        ],
        "tags":
        [
            {
                "name":"lölölöö"
                },
            {
                "name":"äöäöäöä"
                }
        ] 
    } 
}